service: test-app

provider:
    name: aws
    runtime: nodejs18.x
    region: ap-northeast-2
    stage: prod
    memorySize: 128
    timeout: 10
    environment:
        COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
        COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
        ACCOUNT_ID: ${env:ACCOUNT_ID}
    httpApi:
        name: test-app-api
        cors: true
        authorizers:
            cognitoAuthorizer:
                type: jwt
                identitySource: $request.header.Authorization
                issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${self:provider.environment.COGNITO_USER_POOL_ID}
                audience:
                    - ${self:provider.environment.COGNITO_CLIENT_ID}

functions:
    testAppConfirmEmail:
        handler: auth/confirmEmail.handler
        events:
            - httpApi:
                  path: /auth/confirmEmail
                  method: post

    testAppLogin:
        handler: auth/login.handler
        events:
            - httpApi:
                  path: /auth/login
                  method: post

    testAppLogout:
        handler: auth/logout.handler
        events:
            - httpApi:
                  path: /auth/logout
                  method: post

    testAppResendEmail:
        handler: auth/resendEmail.handler
        events:
            - httpApi:
                  path: /auth/resendEmail
                  method: post

    testAppSignup:
        handler: auth/signup.handler
        events:
            - httpApi:
                  path: /auth/signup
                  method: post

    testAppCreatePost:
        handler: crud/createPost.handler
        events:
            - httpApi:
                  path: /posts
                  method: post
                  authorizer: cognitoAuthorizer
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                  Resource:
                      - arn:aws:dynamodb:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:table/Posts
                      - arn:aws:dynamodb:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:table/Counter

    testAppDeletePost:
        handler: crud/deletePost.handler
        events:
            - httpApi:
                  path: /posts/{id}
                  method: delete
                  authorizer: cognitoAuthorizer
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:DeleteItem
                  Resource:
                      - arn:aws:dynamodb:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:table/Posts

    testAppUpdatePost:
        handler: crud/updatePost.handler
        events:
            - httpApi:
                  path: /posts/{id}
                  method: put
                  authorizer: cognitoAuthorizer
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:UpdateItem
                  Resource:
                      - arn:aws:dynamodb:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:table/Posts

    testAppGetPost:
        handler: crud/getPost.handler
        events:
            - httpApi:
                  path: /posts/{id}
                  method: get
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:GetItem
                  Resource:
                      - arn:aws:dynamodb:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:table/Posts

    testAppGetPosts:
        handler: crud/getPosts.handler
        events:
            - httpApi:
                  path: /posts
                  method: get
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:Scan
                  Resource:
                      - arn:aws:dynamodb:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:table/Posts

plugins:
    - serverless-plugin-additional-stacks
