service: acinside-sl-backend

provider:
    name: aws
    runtime: nodejs18.x
    region: ap-northeast-2
    stage: prod
    memorySize: 128
    timeout: 10
    environment:
        COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
        COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
        AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
    httpApi:
        name: acinside-sl-api
        cors: true
        authorizers:
            cognitoAuthorizer:
                type: jwt
                identitySource: '$request.header.Authorization'
                issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${self:provider.environment.COGNITO_USER_POOL_ID}
                audience:
                    - ${self:provider.environment.COGNITO_CLIENT_ID}
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                  Resource:
                      - arn:aws:dynamodb:${self:provider.region}:${self:provider.environment.AWS_ACCOUNT_ID}:table/Posts
                      - arn:aws:dynamodb:${self:provider.region}:${self:provider.environment.AWS_ACCOUNT_ID}:table/Counter
                - Effect: Allow
                  Action:
                      - dynamodb:DeleteItem
                  Resource:
                      - arn:aws:dynamodb:${self:provider.region}:${self:provider.environment.AWS_ACCOUNT_ID}:table/Posts
                - Effect: Allow
                  Action:
                      - dynamodb:GetItem
                  Resource:
                      - arn:aws:dynamodb:${self:provider.region}:${self:provider.environment.AWS_ACCOUNT_ID}:table/Posts
                - Effect: Allow
                  Action:
                      - dynamodb:Scan
                  Resource:
                      - arn:aws:dynamodb:${self:provider.region}:${self:provider.environment.AWS_ACCOUNT_ID}:table/Posts

functions:
    acinsideSL_ConfirmEmail:
        handler: auth/confirmEmail.handler
        events:
            - httpApi:
                  path: /auth/confirmEmail
                  method: post

    acinsideSL_Login:
        handler: auth/login.handler
        events:
            - httpApi:
                  path: /auth/login
                  method: post

    acinsideSL_Logout:
        handler: auth/logout.handler
        events:
            - httpApi:
                  path: /auth/logout
                  method: post

    acinsideSL_ResendEmail:
        handler: auth/resendEmail.handler
        events:
            - httpApi:
                  path: /auth/resendEmail
                  method: post

    acinsideSL_Signup:
        handler: auth/signup.handler
        events:
            - httpApi:
                  path: /auth/signup
                  method: post

    acinsideSL_RefreshToken:
        handler: auth/refresh.handler
        events:
            - httpApi:
                  path: /auth/refresh
                  method: post

    acinsideSL_CreatePost:
        handler: crud/createPost.handler
        events:
            - httpApi:
                  path: /posts
                  method: post
                  authorizer: cognitoAuthorizer

    acinsideSL_DeletePost:
        handler: crud/deletePost.handler
        events:
            - httpApi:
                  path: /posts/{id}
                  method: delete
                  authorizer: cognitoAuthorizer

    acinsideSL_UpdatePost:
        handler: crud/updatePost.handler
        events:
            - httpApi:
                  path: /posts/{id}
                  method: put
                  authorizer: cognitoAuthorizer

    acinsideSL_GetPost:
        handler: crud/getPost.handler
        events:
            - httpApi:
                  path: /posts/{id}
                  method: get

    acinsideSL_GetPosts:
        handler: crud/getPosts.handler
        events:
            - httpApi:
                  path: /posts
                  method: get

plugins:
  - serverless-esbuild
  - serverless-plugin-additional-stacks
  - serverless-prune-plugin

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: 'node18'
    platform: 'node'
    concurrency: 10
    treeShaking: true
    packager: npm
  prune:
    automatic: true
    number: 3

package:
    individually: true
