name: Deploy AWS Lambda functions

on:
    push:
        branches:
            - main
        paths:
            - 'backend/**'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-northeast-2

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Serverless Framework v3
              run: npm install -g serverless@3.40.0

            - name: Install Serverless plugin dependencies
              run: npm install -g serverless-s3-sync serverless-cloudfront-invalidate

            - name: Deploy with Serverless Framework
              run: |
                cd backend
                npx serverless deploy --verbose
              env:
                  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
                  COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
                  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
