name: Deploy AWS Lambda functions

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-northeast-2

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Serverless Framework v3
              run: npm install -g serverless@^3

            - name: Install Serverless plugin dependencies
              run: npm install -g serverless-plugin-additional-stacks

            - name: Deploy with Serverless Framework
              run: npx serverless deploy
              env:
                  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
                  COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
                  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
